pipeline:
 build:
   image: alpine
   commands: echo "hello"

 publish-build-image:
   dockerfile: Dockerfile.build
   image: plugins/docker
   repo: rancher/rancher.github.io
   tag: build
   secrets: [docker_username, docker_password]
   when:
     event: [push, tag]
     branch: master

 publish-docker-image:
   image: plugins/docker
   repo: rancher/rancher.github.io
   tag: latest
   secrets: [docker_username, docker_password]
   when:
     event: [push, tag]
     branch: master
