pipeline:
 build:
   image: alpine
   commands: echo "hello"

 publish-docker-image:
   image: plugins/docker
   repo: rancher/rancher.github.io
   tag: latest
   secrets: [docker_username, docker_password]
   when:
     event: [push, tag]
     branch: master
